# Generated by Django 4.2.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('client_id', models.CharField(help_text='PayPal Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='PayPal Client Secret', max_length=255)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', help_text='PayPal environment mode', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PayPal Configuration',
                'verbose_name_plural': 'PayPal Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Webhook endpoint name', max_length=100)),
                ('url', models.URLField(help_text='Webhook endpoint URL', validators=[django.core.validators.URLValidator()])),
                ('events', models.JSONField(help_text='List of events to listen for')),
                ('webhook_id', models.CharField(blank=True, help_text='PayPal webhook ID', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='PayPal event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('PAYMENT.CAPTURE.COMPLETED', 'Payment Capture Completed'), ('PAYMENT.CAPTURE.DENIED', 'Payment Capture Denied'), ('PAYMENT.CAPTURE.PENDING', 'Payment Capture Pending'), ('PAYMENT.CAPTURE.REFUNDED', 'Payment Capture Refunded'), ('PAYMENT.CAPTURE.REVERSED', 'Payment Capture Reversed'), ('CHECKOUT.ORDER.APPROVED', 'Checkout Order Approved'), ('CHECKOUT.ORDER.COMPLETED', 'Checkout Order Completed'), ('CHECKOUT.ORDER.PROCESSED', 'Checkout Order Processed'), ('BILLING.SUBSCRIPTION.ACTIVATED', 'Billing Subscription Activated'), ('BILLING.SUBSCRIPTION.CANCELLED', 'Billing Subscription Cancelled'), ('BILLING.SUBSCRIPTION.CREATED', 'Billing Subscription Created'), ('BILLING.SUBSCRIPTION.SUSPENDED', 'Billing Subscription Suspended'), ('BILLING.SUBSCRIPTION.UPDATED', 'Billing Subscription Updated')], help_text='Type of webhook event', max_length=100)),
                ('resource_type', models.CharField(help_text='Resource type from PayPal', max_length=100)),
                ('resource_id', models.CharField(help_text='Resource ID from PayPal', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Event summary')),
                ('raw_data', models.JSONField(help_text='Raw webhook data from PayPal')),
                ('processed', models.BooleanField(default=False, help_text='Whether the event has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the event was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type'], name='paypal_pack_event_t_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['processed'], name='paypal_pack_process_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['created_at'], name='paypal_pack_created_123456_idx'),
        ),
    ]
