# Generated by Django 4.2 on 2025-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('your_app_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalconfig',
            name='client_id',
            field=models.CharField(max_length=600, help_text='PayPal Client ID'),
        ),
        migrations.AlterField(
            model_name='paypalconfig',
            name='client_secret',
            field=models.CharField(max_length=600, help_text='PayPal Client Secret'),
        ),
    ]
