# Generated by Django 4.2.7 on 2025-09-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_package', '0002_alter_paypalconfig_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEndpoint',
        ),
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
