# Generated by Django 4.2.7 on 2025-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_package', '0003_delete_webhookendpoint_delete_webhookevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalconfig',
            name='mode',
        ),
        migrations.AddField(
            model_name='paypalconfig',
            name='use_sandbox',
            field=models.BooleanField(default=True, help_text='If enabled, use PayPal Sandbox; if disabled, use Live'),
        ),
        migrations.AlterField(
            model_name='paypalconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this configuration is currently active'),
        ),
    ]
